import type { ServiceDomain, ServiceCategory } from '@/types';

export const domainLabels: Record<ServiceDomain, string> = {
  infrastructure: '인프라',
  backend: '백엔드',
  devtools: '개발도구',
  communication: '커뮤니케이션',
  business: '비즈니스',
  ai_ml: 'AI/ML',
  observability: '옵저버빌리티',
  integration: '통합',
};

export const domainIcons: Record<ServiceDomain, string> = {
  infrastructure: '🏗️',
  backend: '⚙️',
  devtools: '🛠️',
  communication: '💬',
  business: '💼',
  ai_ml: '🧠',
  observability: '🔍',
  integration: '🔗',
};

export const allCategoryLabels: Record<ServiceCategory, string> = {
  auth: '인증',
  social_login: '소셜 로그인',
  database: '데이터베이스',
  deploy: '배포',
  email: '이메일',
  payment: '결제',
  storage: '스토리지',
  monitoring: '모니터링',
  ai: 'AI',
  other: '기타',
  cdn: 'CDN',
  cicd: 'CI/CD',
  testing: '테스팅',
  sms: 'SMS',
  push: '푸시알림',
  chat: '채팅',
  search: '검색',
  cms: 'CMS',
  analytics: '분석',
  media: '미디어',
  queue: '큐',
  cache: '캐시',
  logging: '로깅',
  feature_flags: '피처 플래그',
  scheduling: '스케줄링',
  ecommerce: '이커머스',
  serverless: '서버리스',
  code_quality: '코드 품질',
  automation: '자동화',
};

export const allCategoryEmojis: Record<ServiceCategory, string> = {
  auth: '🔐',
  social_login: '🌐',
  database: '🗄️',
  deploy: '🚀',
  email: '📧',
  payment: '💳',
  storage: '📦',
  monitoring: '📊',
  ai: '🤖',
  other: '🔧',
  cdn: '🌐',
  cicd: '♻️',
  testing: '🧪',
  sms: '📱',
  push: '🔔',
  chat: '💬',
  search: '🔎',
  cms: '📝',
  analytics: '📈',
  media: '🎬',
  queue: '📮',
  cache: '⚡',
  logging: '📋',
  feature_flags: '🏁',
  scheduling: '⏰',
  ecommerce: '🛒',
  serverless: '☁️',
  code_quality: '✅',
  automation: '🤖',
};

export const domainCategoryMap: Record<ServiceDomain, ServiceCategory[]> = {
  infrastructure: ['deploy', 'cdn', 'serverless', 'storage', 'cache'],
  backend: ['database', 'auth', 'social_login', 'queue', 'search', 'cms'],
  devtools: ['cicd', 'testing', 'code_quality', 'logging'],
  communication: ['email', 'sms', 'push', 'chat'],
  business: ['payment', 'ecommerce', 'analytics', 'scheduling'],
  ai_ml: ['ai'],
  observability: ['monitoring', 'logging', 'feature_flags'],
  integration: ['automation', 'other'],
};
