import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { decrypt } from '@/lib/crypto';

export async function GET(request: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const { searchParams } = new URL(request.url);
  const projectId = searchParams.get('project_id');
  const environment = searchParams.get('environment') || 'development';

  if (!projectId) {
    return NextResponse.json({ error: 'Missing project_id' }, { status: 400 });
  }

  // Verify project ownership
  const { data: project } = await supabase
    .from('projects')
    .select('id, name')
    .eq('id', projectId)
    .eq('user_id', user.id)
    .single();

  if (!project) {
    return NextResponse.json({ error: 'Project not found' }, { status: 404 });
  }

  const { data: envVars } = await supabase
    .from('environment_variables')
    .select('*')
    .eq('project_id', projectId)
    .eq('environment', environment)
    .order('key_name');

  if (!envVars || envVars.length === 0) {
    return new NextResponse('# No environment variables found\n', {
      status: 200,
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename=".env.${environment === 'development' ? 'local' : environment}"`,
      },
    });
  }

  const lines: string[] = [
    `# ${project.name} - ${environment} environment`,
    `# Generated by SetLog on ${new Date().toISOString()}`,
    '',
  ];

  for (const envVar of envVars) {
    if (envVar.description) {
      lines.push(`# ${envVar.description}`);
    }
    try {
      const value = decrypt(envVar.encrypted_value);
      lines.push(`${envVar.key_name}=${value}`);
    } catch {
      lines.push(`# ERROR: Could not decrypt ${envVar.key_name}`);
      lines.push(`${envVar.key_name}=`);
    }
    lines.push('');
  }

  const content = lines.join('\n');
  const filename = environment === 'development' ? '.env.local' : `.env.${environment}`;

  return new NextResponse(content, {
    status: 200,
    headers: {
      'Content-Type': 'text/plain',
      'Content-Disposition': `attachment; filename="${filename}"`,
    },
  });
}
